name: example
description: Example project for form_builder_phone_field

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_form_builder:
    git:
      url: https://github.com/Sportner/flutter_form_builder.git
  form_builder_phone_field:
    path: ../

#dependency_overrides:
#  intl: ^0.16.1
#  flutter_datetime_picker:
#    git:
#      url: https://github.com/espresso3389/flutter_datetime_picker

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
